[package]
name = "nanos_ui"
version = "0.1.0"
authors = ["yhql"]
edition = "2018"

[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk", features=["lib_bagl"] } # Enabling lib_bagl on Nano S is a no-op.
