[package]
name = "nanos_ui"
version = "0.2.0"
authors = ["yhql"]
edition = "2021"

[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk" } 
include_gif = { git = "https://github.com/LedgerHQ/sdk_include_gif" }

[features]
speculos = ["nanos_sdk/speculos"]
