[target.nanos]
runner = "python speculos.py --model nanos"

[target.nanox]
runner = "python speculos.py --model nanox"

[target.nanosplus]
runner = "python speculos.py --model nanosplus"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "nanosplus"

[alias]
bns = "build --example gadgets --release --features speculos --target=nanos"
bnsp = "build --example gadgets --release --features speculos --target=nanosplus"
rns = "run --example gadgets --release --features speculos --target=nanos"
rnx = "run --example gadgets --release --features speculos --target=nanox"
rnsp = "run --example gadgets --release --features speculos --target=nanosplus"
