[target.nanos]
runner = "speculos --model nanos"

[target.nanox]
runner = "speculos --model nanox -a 1"

[target.nanosplus]
runner = "speculos --model nanosp -a 1"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "nanosplus"

[alias]
bns = "build --example gadgets --release --features speculos --target=nanos.json"
bnsp = "build --example gadgets --release --features speculos --target=nanosplus.json"
rns = "run --example gadgets --release --features speculos --target=nanos.json"
rnx = "run --example gadgets --release --features speculos --target=nanox.json"
rnsp = "run --example gadgets --release --features speculos --target=nanosplus.json"
